language: php
php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=files_external_ftp
    - DB=sqlite
  matrix:
#    - FTPD=pure-ftpd
    - FTPD=proftpd
    - FTPD=vsftpd

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -yqq bc $FTPD
  - sudo /etc/init.d/$FTPD restart
  - if [ "$FTPD" = "vsftpd" ]; then echo "local_enable=YES" | sudo tee -a /etc/vsftpd.conf; echo "write_enable=YES" | sudo tee -a /etc/vsftpd.conf; fi
  - sudo /etc/init.d/$FTPD restart

  - pass=$(perl -e 'print crypt("test", "password")')
  - sudo useradd -m -p $pass test

  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable files_external
  - php occ app:enable $APP_NAME

script:
  # Test lint
  - cd ../core/apps/$APP_NAME
  - find . -name \*.php -exec php -l "{}" \;

  # Run phpunit tests
  - cd tests
  - echo '{"host":"localhost","username":"test","password":"test"}' > config.json
  - phpunit --configuration phpunit.xml

  # Create coverage report
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"

matrix:
  fast_finish: true
